version: "3.3"

services:
  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  wordpress:
    image: wordpress:6-apache
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${WP_PORT:-8080}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', '${WP_HOME:-http://localhost:8080}');
        define('WP_SITEURL', '${WP_HOME:-http://localhost:8080}');
    volumes:
      - wordpress_data:/var/www/html
      - ./sesna-v2:/var/www/html/wp-content/themes/sesna-v2
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini

  wpcli:
    image: wordpress:cli
    depends_on:
      - db
      - wordpress
    user: "33:33"
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - wordpress_data:/var/www/html
      - ./sesna-v2:/var/www/html/wp-content/themes/sesna-v2
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  db_data:
  wordpress_data:
